name: CI

on:
  schedule:
    - cron: 00 01,07,13,19 * * *
  workflow_dispatch:

jobs:
  mirror:
    name: ${{ matrix.SUBDIR }}
    runs-on: ubuntu-latest
    env:
      SUBDIR: ${{ matrix.SUBDIR }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - SUBDIR: noarch
          - SUBDIR: win-64
          - SUBDIR: linux-64
          - SUBDIR: linux-aarch64
          - SUBDIR: osx-64
          - SUBDIR: osx-arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10
        
    - name: Mirror ${{ matrix.SUBDIR }} packages
      shell: bash -l {0}
      env:
        ANACONDA_UPLOAD_TOKEN: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
      run: |
        mkdir -p sandbox
        cd sandbox
        python -u ../scripts/mirror.py $SUBDIR -t $ANACONDA_UPLOAD_TOKEN
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.SUBDIR }}_mirrored_packages
        path: sandbox/

    - name: Cleanup
      shell: bash -l {0}
      run: rm -rf sandbox
