name: CI

on:
  schedule:
    - cron: 00 01,07,13,19 * * *
  workflow_dispatch:

jobs:
  mirror:
    name: conda-mirror-bot
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mamba & environment
      uses: mamba-org/provision-with-micromamba@v10
        
    - name: Mirror packages
      env:
        SEMIATE_UPLOAD_TOKEN: ${{ secrets.SEMIATE_UPLOAD_TOKEN }}
        NEROHMOT_UPLOAD_TOLEN: ${{ secrets.NEROHMOT_UPLOAD_TOLEN }}
      run: python -u mirror.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: new_uploads
        path: download/
        
